name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - uses: dioptra-io/setup-poetry-action@v1
      - name: Install package
        run: poetry install
          # - name: Run tests
          # run: sudo --preserve-env=CI,RIPE_ATLAS_KEY $(poetry env info -p)/bin/pytest --cov=iris --cov-report=xml --log-cli-level=INFO
      - uses: codecov/codecov-action@v3

  docker:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dioptra-io/publish-docker-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
